apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: test-set3
spec:
  providers:
    - name: gcp-1
      providerType: gcp
      secretRef:
        name: gcp-secret
        namespace: e2e-secrets
    - name: hetznerdns-1
      providerType: hetznerdns
      secretRef:
        name: hetznerdns-secret
        namespace: e2e-secrets
    - name: oci-1
      providerType: oci
      secretRef:
        name: oci-secret
        namespace: e2e-secrets
    - name: genesiscloud-1
      providerType: genesiscloud
      secretRef:
        name: genesiscloud-secret
        namespace: e2e-secrets
    - name: aws-1
      providerType: aws
      secretRef:
        name: aws-secret
        namespace: e2e-secrets
    - name: cloudflare-1
      providerType: cloudflare
      secretRef:
        name: cloudflare-secret
        namespace: e2e-secrets        
  nodePools:
    dynamic:
      - name: oci-kube-nodes
        providerSpec:
          name: oci-1
          region: eu-frankfurt-1
          zone: hsVQ:EU-FRANKFURT-1-AD-3
        count: 1
        serverType: VM.Standard.E4.Flex
        machineSpec:
          # use 2 ocpus.
          cpuCount: 2
          # use 8 gb of memory.
          memory: 8
        # ubuntu minimal
        # https://docs.oracle.com/en-us/iaas/images/ubuntu-2404/canonical-ubuntu-24-04-2024-08-28-0.htm
        image: ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa7hxwyz4qiasffo7n7s4ep5lywpzwgkc2am65frqrqinoyitmxxla
        storageDiskSize: 50

      - name: aws-kube-nodes
        providerSpec:
          name: aws-1
          region: eu-west-2
          zone: eu-west-2a
        count: 1
        serverType: t3.small
        #ubuntu
        image: ami-0e8d228ad90af673b
        storageDiskSize: 50

      - name: gen-kube-nodes
        providerSpec:
          name: genesiscloud-1
          region: NORD-NO-KRS-1
        count: 2
        serverType: vcpu-2_memory-4g
        image: "Ubuntu 24.04"
        storageDiskSize: 50

      - name: gcp-ctrl-nodes
        providerSpec:
          name: gcp-1
          region: europe-west2
          zone: europe-west2-c
        count: 1
        serverType: e2-medium
        image: ubuntu-minimal-2404-noble-amd64-v20241116
        storageDiskSize: 50
      - name: gcp-cmpt-nodes
        providerSpec:
          name: gcp-1
          region: europe-west1
          zone: europe-west1-b
        count: 2
        serverType: e2-small
        image: ubuntu-minimal-2404-noble-amd64-v20241116
        storageDiskSize: 50

      #-----------LB nodepools----------
      - name: gcp-ldbl-nodes
        providerSpec:
          name: gcp-1
          region: europe-west1
          zone: europe-west1-c
        count: 1
        serverType: e2-small
        image: ubuntu-minimal-2404-noble-amd64-v20241116
        storageDiskSize: 50

  kubernetes:
    clusters:
      - name: ts3-c-1-cluster-test-set-no3
        version: 1.29.0
        network: 192.168.2.0/24
        pools:
          control:
            - gen-kube-nodes
          compute:
            - gen-kube-nodes
      - name: ts3-c-2-cluster-test-set-no3
        version: 1.29.0
        network: 192.168.2.0/24
        installationProxy:
          mode: "on"
        pools:
          control:
            - gen-kube-nodes
            - gcp-ctrl-nodes
            - oci-kube-nodes
          compute:
            - gen-kube-nodes
            - gcp-cmpt-nodes
            - aws-kube-nodes
  loadBalancers:
    roles:
      - name: apiserver-lb
        protocol: tcp
        port: 6443
        targetPort: 6443
        targetPools:
          - gen-kube-nodes
      - name: apiserver-lb-2
        protocol: tcp
        port: 6443
        targetPort: 6443
        targetPools:
          - gen-kube-nodes
          - gcp-ctrl-nodes
          - oci-kube-nodes
    clusters:
      - name: ts3-lb1-cluster-test-set-no3
        roles:
          - apiserver-lb
        dns:
          dnsZone: claudie.dev
          provider: cloudflare-1
        targetedK8s: ts3-c-1-cluster-test-set-no3
        pools:
          - gcp-ldbl-nodes
      - name: ts3-lb2-cluster-test-set-no3
        roles:
          - apiserver-lb-2
        dns:
          dnsZone: claudie.org
          provider: hetznerdns-1
        targetedK8s: ts3-c-2-cluster-test-set-no3
        pools:
          - gcp-ldbl-nodes
