apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: test-set3
spec:
  providers:
    - name: gcp-1
      providerType: gcp
      secretRef:
        name: gcp-secret
        namespace: e2e-secrets
    - name: hetzner-1
      providerType: hetzner
      secretRef:
        name: hetzner-secret
        namespace: e2e-secrets   
    - name: hetznerdns-1
      providerType: hetznerdns
      secretRef:
        name: hetznerdns-secret
        namespace: e2e-secrets
    - name: oci-1
      providerType: oci
      secretRef:
        name: oci-secret
        namespace: e2e-secrets
    - name: aws-1
      providerType: aws
      secretRef:
        name: aws-secret
        namespace: e2e-secrets
    - name: cloudflare-1
      providerType: cloudflare
      secretRef:
        name: cloudflare-secret
        namespace: e2e-secrets        
  nodePools:
    dynamic:
      - name: hetzner-control
        providerSpec:
          name: hetzner-1
          region: fsn1
          zone: fsn1-dc14
        count: 1
        serverType: cpx11
        image: ubuntu-22.04
        storageDiskSize: 50
      - name: hetzner-compute
        providerSpec:
          name: hetzner-1
          region: fsn1
          zone: fsn1-dc14
        count: 1
        serverType: cpx11
        image: ubuntu-22.04
        storageDiskSize: 50

      - name: oci-control
        providerSpec:
          name: oci-1
          region: eu-frankfurt-1
          zone: hsVQ:EU-FRANKFURT-1-AD-3
        count: 1
        serverType: VM.Standard2.1
        # ubuntu minimal
        # https://docs.oracle.com/en-us/iaas/images/image/674d0b41-aee8-4c0b-bf99-9e100d90f241/
        image: ocid1.image.oc1.eu-frankfurt-1.aaaaaaaavvsjwcjstxt4sb25na65yx6i34bzdy5oess3pkgwyfa4hxmzpqeq
        storageDiskSize: 50
      - name: oci-compute
        providerSpec:
          name: oci-1
          region: eu-frankfurt-1
          zone: hsVQ:EU-FRANKFURT-1-AD-3
        count: 1
        serverType: VM.Standard1.1
        # ubuntu minimal
        # https://docs.oracle.com/en-us/iaas/images/image/674d0b41-aee8-4c0b-bf99-9e100d90f241/
        image: ocid1.image.oc1.eu-frankfurt-1.aaaaaaaavvsjwcjstxt4sb25na65yx6i34bzdy5oess3pkgwyfa4hxmzpqeq
        storageDiskSize: 50

      - name: aws-control
        providerSpec:
          name: aws-1
          region: eu-west-2
          zone: eu-west-2a
        count: 1
        serverType: t3.small
        #ubuntu
        image: ami-01b8d743224353ffe
        storageDiskSize: 50
      - name: aws-compute
        providerSpec:
          name: aws-1
          region: eu-west-2
          zone: eu-west-2a
        count: 1
        serverType: t3.small
        #ubuntu
        image: ami-01b8d743224353ffe
        storageDiskSize: 50

      - name: gcp-control
        providerSpec:
          name: gcp-1
          region: europe-west2
          zone: europe-west2-c
        count: 1
        serverType: e2-medium
        image: ubuntu-os-cloud/ubuntu-2204-jammy-v20221206
        storageDiskSize: 50
      - name: gcp-compute
        providerSpec:
          name: gcp-1
          region: europe-west1
          zone: europe-west1-b
        count: 2
        serverType: e2-small
        image: ubuntu-os-cloud/ubuntu-2204-jammy-v20221206
        storageDiskSize: 50

      #-----------LB nodepools----------
      - name: gcp-lb
        providerSpec:
          name: gcp-1
          region: europe-west1
          zone: europe-west1-c
        count: 1
        serverType: e2-small
        image: ubuntu-os-cloud/ubuntu-2204-jammy-v20221206
        storageDiskSize: 50

  kubernetes:
    clusters:
      - name: ts3-c-1
        version: v1.24.0
        network: 192.168.2.0/24
        pools:
          control:
            - hetzner-control
            - oci-control
            - aws-control
          compute:
            - hetzner-compute
            - oci-compute
            - aws-compute
      - name: ts3-c-2
        version: v1.24.0
        network: 192.168.2.0/24
        pools:
          control:
            - aws-control
            - gcp-control
            - oci-control
          compute:
            - aws-compute
            - gcp-compute
            - oci-compute
  loadBalancers:
    roles:
      - name: apiserver-lb
        protocol: tcp
        port: 6443
        targetPort: 6443
        target: k8sControlPlane
    clusters:
      - name: ts3-lb-1
        roles:
          - apiserver-lb
        dns:
          dnsZone: claudie.dev
          provider: cloudflare-1
        targetedK8s: ts3-c-1
        pools:
          - gcp-lb
      - name: ts3-lb-2
        roles:
          - apiserver-lb
        dns:
          dnsZone: claudie.org
          provider: hetznerdns-1
        targetedK8s: ts3-c-2
        pools:
          - gcp-lb
