apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: autoscaling-1
spec:
  providers:
    - name: gcp-1
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.15
        path: "templates/terraformer/gcp"
      providerType: gcp
      secretRef:
        name: gcp-secret
        namespace: e2e-secrets
    - name: gcp-2
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.15
        path: "templates/terraformer/gcp"
      providerType: gcp
      secretRef:
        name: gcp-secret
        namespace: e2e-secrets
  nodePools:
    dynamic:
      - name: gcp-ctrl-nodes
        providerSpec:
          name: gcp-1
          region: europe-west1
          zone: europe-west1-c
        count: 1
        serverType: e2-medium
        image: ubuntu-2404-noble-amd64-v20251001
        storageDiskSize: 50
      - name: gcp-cmpt-nodes
        providerSpec:
          name: gcp-2
          region: europe-west2
          zone: europe-west2-a
        autoscaler:
          min: 1
          max: 5
        serverType: e2-medium
        image: ubuntu-2404-noble-amd64-v20251001
        storageDiskSize: 50

  kubernetes:
    clusters:
      - name: autoscaling-cluster-test-set
        version: "1.34.0"
        network: 192.168.2.0/24
        pools:
          control:
            - gcp-ctrl-nodes
          compute:
            - gcp-cmpt-nodes
