apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: autoscaling-2
spec:
  providers:
    - name: aws-1
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: "v0.9.12"
        path: "templates/terraformer/aws"
      providerType: aws
      secretRef:
        name: aws-secret
        namespace: e2e-secrets
    - name: aws-2
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: "v0.9.12"
        path: "templates/terraformer/aws"
      providerType: aws
      secretRef:
        name: aws-secret
        namespace: e2e-secrets
  nodePools:
    dynamic:
      - name: aws-ctrl-nodes
        providerSpec:
          name: aws-1
          region: eu-north-1
          zone: eu-north-1a
        count: 1
        serverType: t3.medium
        #ubuntu
        image: ami-08eb150f611ca277f
        taints:
          - key: test
            value: test
            effect: NoSchedule

      - name: aws-cmpt-nodes
        providerSpec:
          name: aws-2
          region: eu-west-3
          zone: eu-west-3a
        autoscaler:
          min: 1
          max: 5
        serverType: t3.medium
        #ubuntu
        image: ami-045a8ab02aadf4f88
        storageDiskSize: 50
        labels:
          test-set: autoscaling-2
        annotations:
          test-set: autoscaling-2

  kubernetes:
    clusters:
      - name: autoscaling-cluster-test-002
        version: "1.34.0"
        network: 192.168.2.0/24
        pools:
          control:
            - aws-ctrl-nodes
          compute:
            - aws-cmpt-nodes
