apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: succeeds-on-last-2
spec:
  providers:
    - name: hetzner-1
      providerType: hetzner
      templates:
        repository: "https://github.com/berops/claudie-config"
        path: "templates/terraformer/hetzner"
      secretRef:
        name: hetzner-secret
        namespace: e2e-secrets
    - name: oci-1
      providerType: oci
      templates:
        repository: "https://github.com/berops/claudie-config"
        path: "templates/terraformer/oci"
      secretRef:
        name: oci-secret
        namespace: e2e-secrets
  nodePools:
    dynamic:
      - name: htz-nodes
        providerSpec:
          name: hetzner-1
          region: nbg1
          zone: nbg1-dc3
        count: 1
        serverType: cpx11
        image: ubuntu-24.04
      - name: oci-cmpt-00001
        providerSpec:
          name: oci-1
          region: eu-frankfurt-1
          zone: hsVQ:EU-FRANKFURT-1-AD-1
        count: 1
        serverType: VM.Standard1.1
        # ubuntu minimal - wrong image
        # https://docs.oracle.com/en-us/iaas/images/ubuntu-2404/canonical-ubuntu-24-04-2024-08-28-0.htm
        image: ocid1.image.oc1.eu-frankfurt-1.000000000000000000000000000000000000000000000000000000000001
        storageDiskSize: 50
  kubernetes:
    clusters:
      - name: succeeds-on-last-2-cluster-0
        version: 1.29.0
        network: 192.168.2.0/24
        pools:
          control:
            - htz-nodes
          compute:
            - oci-cmpt-00001
