apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: exoscale-1
spec:
  providers:
    - name: exoscale-1
      providerType: exoscale
      templates:
        repository: "https://github.com/samuelstolicny/claudie-config"
        tag: v0.9.17
        path: "templates/terraformer/exoscale"
      secretRef:
        name: exoscale-secret
        namespace: e2e-secrets
  nodePools:
    dynamic:
      - name: exo-ctrl-nodes
        providerSpec:
          name: exoscale-1
          region: ch-gva-2
        count: 1
        serverType: standard.medium
        image: "Linux Ubuntu 24.04 LTS 64-bit"
        labels:
          test-set: exoscale-1
      - name: exo-gpu-nodes
        providerSpec:
          name: exoscale-1
          region: at-vie-1
        count: 1
        serverType: gpu2.small
        image: "Linux Ubuntu 24.04 LTS 64-bit"
        storageDiskSize: 50
        labels:
          test-set: exoscale-1
  kubernetes:
    clusters:
      - name: exo-cluster-exoscale-no1
        version: "1.34.0"
        network: 192.168.2.0/24
        pools:
          control:
            - exo-ctrl-nodes
          compute:
            - exo-gpu-nodes
