apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: proxy-with-hetzner
spec:
  providers:
    - name: hetzner-1
      providerType: hetzner
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.19
        path: "templates/terraformer/hetzner"
      secretRef:
        name: hetzner-secret
        namespace: e2e-secrets
  nodePools:
    dynamic:
      - name: htz-ctrl-nodes
        providerSpec:
          name: hetzner-1
          region: fsn1
          zone: fsn1-dc14
        count: 1
        serverType: cpx22
        image: ubuntu-24.04
        storageDiskSize: 50
        labels:
          test-set: proxy-with-hetzner
        annotations:
          claudie.io/example-annotation: >
            ["proxy-with-hetzner"]
      - name: htz-cmpt-nodes
        providerSpec:
          name: hetzner-1
          region: fsn1
          zone: fsn1-dc14
        serverType: cpx22
        image: ubuntu-24.04
        storageDiskSize: 50
        count: 1
        labels:
          test-set: proxy-with-hetzner
        annotations:
          claudie.io/example-annotation: >
            ["proxy-with-hetzner"]
  kubernetes:
    clusters:
      - name: proxy-with-hetzner
        version: "1.34.0"
        network: 192.168.2.0/24
        installationProxy:
          mode: "default"
          endpoint: http://proxy.claudie.io:8880
        pools:
          control:
            - htz-ctrl-nodes
          compute:
            - htz-cmpt-nodes
