# Make sure longhorn is deployed only on compute nodes
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: system-managed-components-node-selector
  namespace: longhorn-system
value: claudie.io/node-type:compute
---
# Make sure longhorn is using block on eviction if last replica is on the node deleted.
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: node-drain-policy
  namespace: longhorn-system
value: block-for-eviction-if-last-replica
---
# Default path to use for storing data on a host
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: default-data-path
  namespace: longhorn-system
value: /opt/claudie/data
---
# Default data locality setting to use best-effort
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: default-data-locality
  namespace: longhorn-system
value: best-effort