apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansibler
  labels:
    app.kubernetes.io/part-of: claudie
    app.kubernetes.io/name: ansibler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: claudie
      app.kubernetes.io/name: ansibler
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: claudie
        app.kubernetes.io/name: ansibler
    spec:
      terminationGracePeriodSeconds: 1320
      securityContext:
        runAsUser: 65534
        runAsGroup: 3000
        fsGroup: 2000
      volumes:
        - name: data
          emptyDir: { }
        - name: temp
          emptyDir: { }
      containers:
        - name: ansibler
          volumeMounts:
            - mountPath: /bin/services/ansibler/server/clusters
              name: data
            - mountPath: /.ansible
              name: temp
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
          imagePullPolicy: Always
          image: ghcr.io/berops/claudie/ansibler
          resources:
            requests:
              cpu: 200m
              memory: 600Mi
            limits:
              memory: 800Mi
          env:
            - name: ANSIBLER_PORT
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: ANSIBLER_PORT
              # No hostname needed
            - name: GOLANG_LOG
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: GOLANG_LOG
          ports:
            - containerPort: 50053
            - name: "metrics"
              containerPort: 9090
          readinessProbe:
            grpc:
              port: 50053
              service: ansibler-readiness
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            grpc:
              port: 50053
              service: ansibler-liveness
            initialDelaySeconds: 5
            periodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  name: ansibler
  labels:
    app.kubernetes.io/part-of: claudie
    app.kubernetes.io/name: ansibler
spec:
  selector:
    app.kubernetes.io/part-of: claudie
    app.kubernetes.io/name: ansibler
  ports:
    - protocol: TCP
      port: 50053
      targetPort: 50053
