apiVersion: apps/v1
kind: Deployment
metadata:
  name: context-box
  labels:
    app.kubernetes.io/part-of: claudie
    app: context-box
    app.kubernetes.io/name: context-box
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: claudie
      app: context-box
      app.kubernetes.io/name: context-box
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: claudie
        app: context-box
        app.kubernetes.io/name: context-box
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: context-box
          imagePullPolicy: Always
          image: ghcr.io/berops/claudie/context-box
          resources:
            requests:
              cpu: 80m
              memory: 50Mi
            limits:
              cpu: 160m
              memory: 100Mi
          env:
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: DATABASE_PORT
            - name: DATABASE_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: DATABASE_HOSTNAME
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: CONTEXT_BOX_PORT
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: CONTEXT_BOX_PORT
              # No hostname needed
            - name: GOLANG_LOG
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: GOLANG_LOG
          ports:
            - containerPort: 50055
          readinessProbe:
            grpc:
              port: 50055
              service: context-box-readiness
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            grpc:
              port: 50055
              service: context-box-liveness
            initialDelaySeconds: 5
            periodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  name: context-box
  labels:
    app.kubernetes.io/part-of: claudie
    app: context-box
    app.kubernetes.io/name: context-box
spec:
  selector:
    app.kubernetes.io/part-of: claudie
    app: context-box
    app.kubernetes.io/name: context-box
  ports:
    - protocol: TCP
      port: 50055
      targetPort: 50055
