apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraformer
  labels:
    app: terraformer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraformer
  template:
    metadata:
      labels:
        app: terraformer
    spec:
      terminationGracePeriodSeconds: 1320
      containers:
        - name: terraformer
          imagePullPolicy: Always
          image: claudieio/terraformer
          resources:
            requests:
              cpu: 700m
              memory: 768Mi
            limits:
              cpu: 1024m
              memory: 1248Mi
          env:
            - name: TERRAFORMER_PORT
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: TERRAFORMER_PORT
              # No hostname needed
            - name: GOLANG_LOG
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: GOLANG_LOG
            # MinIO envs
            - name: MINIO_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: MINIO_HOSTNAME
            - name: MINIO_PORT
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: MINIO_PORT
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_PASSWORD
            # DynamoDB envs
            - name: DYNAMO_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: DYNAMO_HOSTNAME
            - name: DYNAMO_PORT
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: DYNAMO_PORT
            - name: DYNAMO_TABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: DYNAMO_TABLE_NAME
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: AWS_REGION
          ports:
            - containerPort: 50052
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50052"]
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe-Liveness", "-addr=:50052"]
            initialDelaySeconds: 30
            periodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  name: terraformer
spec:
  selector:
    app: terraformer
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
