apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraformer
  labels:
    app.kubernetes.io/part-of: claudie
    app.kubernetes.io/name: terraformer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: claudie
      app.kubernetes.io/name: terraformer
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: claudie
        app.kubernetes.io/name: terraformer
    spec:
      terminationGracePeriodSeconds: 1320
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      volumes:
        - name: data
          emptyDir: { }
        - name: temp
          emptyDir: { }
      containers:
        - name: terraformer
          imagePullPolicy: Always
          image: ghcr.io/berops/claudie/terraformer
          volumeMounts:
            - mountPath: /bin/services/terraformer/server/clusters
              name: data
            - mountPath: /tmp
              name: temp
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
          resources:
            requests:
              cpu: 200m
              memory: 1200Mi
            limits:
              memory: 1500Mi
          env:
            - name: TERRAFORMER_PORT
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: TERRAFORMER_PORT
              # No hostname needed
            - name: GOLANG_LOG
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: GOLANG_LOG
            # Bucket envs - default to local MinIO
            # It will use AWS Credentials to auth to MinIO
            - name: BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: BUCKET_NAME
            - name: BUCKET_URL
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: BUCKET_URL
            # DynamoDB envs
            - name: DYNAMO_URL
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: DYNAMO_URL
            - name: DYNAMO_TABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: DYNAMO_TABLE_NAME
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: AWS_REGION
          ports:
            - containerPort: 50052
            - name: "metrics"
              containerPort: 9090
          readinessProbe:
            grpc:
              port: 50052
              service: terraformer-readiness
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            grpc:
              port: 50052
              service: terraformer-liveness
            initialDelaySeconds: 5
            periodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  name: terraformer
  labels:
    app.kubernetes.io/part-of: claudie
    app.kubernetes.io/name: terraformer
spec:
  selector:
    app.kubernetes.io/part-of: claudie
    app.kubernetes.io/name: terraformer
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
