apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: succeeds-on-last-4
spec:
  providers:
    - name: hetzner-1
      providerType: hetzner
      templates:
        repository: "https://github.com/berops/claudie-config"
        path: "templates/terraformer/hetzner"
      secretRef:
        name: hetzner-secret
        namespace: e2e-secrets
    - name: azure-sponsor-1
      providerType: azure
      templates:
        repository: "https://github.com/berops/claudie-config"
        path: "templates/terraformer/azure"
      secretRef:
        name: azure-sponsorship-secret
        namespace: e2e-secrets
    - name: hetznerdns-1
      providerType: hetznerdns
      secretRef:
        name: hetznerdns-secret
        namespace: e2e-secrets
  nodePools:
    dynamic:
      - name: azr-nodes
        providerSpec:
          name: azure-sponsor-1
          region: Germany West Central
          zone: "3"
        count: 1
        serverType: Standard_B2s
        image: Canonical:0001-com-test00-minimal-jammy:minimal-22_04-lts:22.04.202212120 # image doesnt exist
        storageDiskSize: 50
      - name: htz-ctrl-nodes
        providerSpec:
          name: hetzner-1
          region: nbg1
          zone: nbg1-dc3
        count: 1
        serverType: cpx11
        image: ubuntu-24.04
  kubernetes:
    clusters:
      - name: succeeds-on-last-4-cluster-0
        version: 1.29.0
        network: 192.168.2.0/24
        pools:
          control:
            - htz-ctrl-nodes
          compute:
            - htz-ctrl-nodes
  loadBalancers:
    roles:
      - name: apiserver-lb-hetzner
        protocol: tcp
        port: 6443
        targetPort: 6443
        targetPools:
          - htz-ctrl-nodes
      - name: lb-htz
        protocol: tcp
        port: 6447
        targetPort: 6447
        targetPools:
          - htz-ctrl-nodes
    clusters:
      - name: succeeds-on-last-4-lb0000001
        roles:
          - apiserver-lb-hetzner
        dns:
          dnsZone: claudie.org
          provider: hetznerdns-1
        targetedK8s: succeeds-on-last-4-cluster-0
        pools:
          - azr-nodes
      - name: succeeds-on-last-4-lb0000002
        roles:
          - lb-htz
        dns:
          dnsZone: claudie.org
          provider: hetznerdns-1
        targetedK8s: succeeds-on-last-4-cluster-0
        pools:
          - htz-ctrl-nodes
