apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: test-set1
spec:
  providers:
    - name: gcp-1
      providerType: gcp
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.15
        path: "templates/terraformer/gcp"
      secretRef:
        name: gcp-secret
        namespace: e2e-secrets
    - name: hetzner-1
      providerType: hetzner
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.15
        path: "templates/terraformer/hetzner"
      secretRef:
        name: hetzner-secret
        namespace: e2e-secrets
    - name: oci-1
      providerType: oci
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.15
        path: "templates/terraformer/oci"
      secretRef:
        name: oci-secret
        namespace: e2e-secrets
    - name: aws-1
      providerType: aws
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.15
        path: "templates/terraformer/aws"
      secretRef:
        name: aws-secret
        namespace: e2e-secrets
    - name: aws-2
      providerType: aws
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.15
        path: "templates/terraformer/aws"
      secretRef:
        name: aws-secret
        namespace: e2e-secrets
    - name: azure-sponsor-1
      providerType: azure
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.15
        path: "templates/terraformer/azure"
      secretRef:
        name: azure-sponsorship-secret
        namespace: e2e-secrets
    - name: azure-sponsor-2
      providerType: azure
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.15
        path: "templates/terraformer/azure"
      secretRef:
        name: azure-sponsorship-secret
        namespace: e2e-secrets
    - name: ovh-1
      providerType: openstack
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.15
        path: "templates/terraformer/openstack"
      secretRef:
        name: ovh-secret
        namespace: e2e-secrets
  nodePools:
    dynamic:
      - name: htz-ctrl-nodes
        providerSpec:
          name: hetzner-1
          region: nbg1
          zone: nbg1-dc3
        count: 1
        serverType: cpx32
        image: ubuntu-24.04
        labels:
          test-set: test-set1
        annotations:
          claudie.io/example-annotation: >
            ["test-set1"]
      - name: htz-cmpt-nodes
        providerSpec:
          name: hetzner-1
          region: nbg1
          zone: nbg1-dc3
        count: 1
        serverType: cpx32
        image: ubuntu-24.04
        storageDiskSize: 50
        labels:
          test-set: test-set1
        annotations:
          claudie.io/example-annotation: >
            ["test-set1"]

      - name: gcp-ctrl-nodes
        providerSpec:
          name: gcp-1
          region: europe-west2
          zone: europe-west2-c
        count: 3
        serverType: e2-highcpu-4
        image: ubuntu-2404-noble-amd64-v20251001
        labels:
          test-set: test-set1
      - name: gcp-cmpt-nodes
        providerSpec:
          name: gcp-1
          region: europe-west1
          zone: europe-west1-b
        count: 3
        serverType: e2-standard-4
        image: ubuntu-2404-noble-amd64-v20251001
        storageDiskSize: 50
        labels:
          test-set: test-set1
        annotations:
          claudie.io/example-annotation: >
            ["test-set1"]

      - name: oci-ctrl-nodes
        providerSpec:
          name: oci-1
          region: eu-frankfurt-1
          zone: hsVQ:EU-FRANKFURT-1-AD-1
        count: 3
        serverType: VM.Standard.E4.Flex
        machineSpec:
          # use 2 ocpus are equal to 4 vCPUs
          # https://docs.oracle.com/en-us/iaas/Content/Compute/References/computeshapes.htm
          cpuCount: 2
          # use 4 gb of memory.
          memory: 4
        # https://docs.oracle.com/en-us/iaas/images/ubuntu-2404/canonical-ubuntu-24-04-2024-08-28-0.htm
        image: ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa7hxwyz4qiasffo7n7s4ep5lywpzwgkc2am65frqrqinoyitmxxla
        taints:
          - key: test
            effect: NoSchedule
      - name: oci-cmpt-nodes
        providerSpec:
          name: oci-1
          region: eu-frankfurt-1
          zone: hsVQ:EU-FRANKFURT-1-AD-1
        count: 3
        serverType: VM.Standard.E4.Flex
        machineSpec:
          # use 2 ocpus are equal to 4 vCPUs
          # https://docs.oracle.com/en-us/iaas/Content/Compute/References/computeshapes.htm
          cpuCount: 2
          # use 4 gb of memory.
          memory: 4
        # https://docs.oracle.com/en-us/iaas/images/ubuntu-2404/canonical-ubuntu-24-04-2024-08-28-0.htm
        image: ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa7hxwyz4qiasffo7n7s4ep5lywpzwgkc2am65frqrqinoyitmxxla
        storageDiskSize: 50

      - name: aws-ctrl-nodes
        providerSpec:
          name: aws-1
          region: eu-north-1
          zone: eu-north-1a
        count: 3
        serverType: t3.xlarge
        #ubuntu
        image: ami-08eb150f611ca277f
        taints:
          - key: test
            value: test
            effect: NoSchedule
      - name: aws-cmpt-nodes
        providerSpec:
          name: aws-2
          region: eu-west-3
          zone: eu-west-3a
        count: 3
        serverType: t3.xlarge
        #ubuntu
        image: ami-045a8ab02aadf4f88
        storageDiskSize: 50

      - name: azr-ctrl-nodes
        providerSpec:
          name: azure-sponsor-2
          region: Germany West Central
          zone: "1"
        count: 2
        serverType: Standard_B4ls_v2
        image: Canonical:ubuntu-24_04-lts:server:24.04.202510010
        taints:
          - key: test
            value: test
            effect: NoSchedule
        labels:
          test-set: test-set1
        annotations:
          claudie.io/example-annotation: >
            ["test-set1"]
      - name: azr-cmpt-nodes
        providerSpec:
          name: azure-sponsor-1
          region: Germany West Central
          zone: "1"
        count: 2
        serverType: Standard_B4ls_v2
        image: Canonical:ubuntu-24_04-lts:server:24.04.202510010
        storageDiskSize: 50
        labels:
          test-set: test-set1
        annotations:
          claudie.io/example-annotation: >
            ["test-set1"]
      - name: ovh-ctrl-nodes
        providerSpec:
          name: ovh-1
          region: DE1
          zone: nova
          externalNetworkName: Ext-Net
        count: 1
        serverType: c3-8-flex
        image: "Ubuntu 24.04"
        taints:
          - key: test
            value: test
            effect: NoSchedule
        labels:
          test-set: test-set1
        annotations:
          claudie.io/example-annotation: >
            ["test-set1"]
      - name: ovh-cmpt-nodes
        providerSpec:
          name: ovh-1
          region: RBX-A
          zone: nova
          externalNetworkName: Ext-Net
        count: 1
        serverType: c3-8-flex
        image: "Ubuntu 24.04"
        storageDiskSize: 50
        labels:
          test-set: test-set1
        annotations:
          claudie.io/example-annotation: >
            ["test-set1"]
  kubernetes:
    clusters:
      - name: ts1-htz-cluster-test-set-no1
        version: "1.34.0"
        network: 192.168.2.0/24
        pools:
          control:
            - htz-ctrl-nodes
          compute:
            - htz-cmpt-nodes
      - name: ts1-gcp-cluster-test-set-no1
        version: "1.34.0"
        network: 192.168.2.0/24
        pools:
          control:
            - gcp-ctrl-nodes
          compute:
            - gcp-cmpt-nodes
      - name: ts1-oci-cluster-test-set-no1
        version: "1.34.0"
        network: 192.168.2.0/24
        installationProxy:
          mode: "on"
        pools:
          control:
            - oci-ctrl-nodes
          compute:
            - oci-cmpt-nodes
      - name: ts1-aws-cluster-test-set-no1
        version: "1.34.0"
        network: 192.168.2.0/24
        pools:
          control:
            - aws-ctrl-nodes
          compute:
            - aws-cmpt-nodes
      - name: ts1-azr-cluster-test-set-no1
        version: "1.34.0"
        network: 192.168.2.0/24
        pools:
          control:
            - azr-ctrl-nodes
          compute:
            - azr-cmpt-nodes
      - name: ts1-ovh-cluster-test-set-no1
        version: "1.34.0"
        network: 192.168.2.0/24
        installationProxy:
          mode: "on"
        pools:
          control:
            - ovh-ctrl-nodes
          compute:
            - ovh-cmpt-nodes
